
/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Jun 10 2019
 * Processor: LPC2138
 * Compiler:  GCC for ARM
 */

#include <LPC213x.h>

#define DELAY 30000

void delay (int time) 
{
	int d;
	
	for(d = 0; d < time; d++);

}

int main (void)
{
	/* Define the LED pins P1 . [ 1 6 . . 2 2 ] as output */
	IODIR1 = 0x0FFFF000 ;
	
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x08000000 ;
	delay(DELAY);
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x0C000000 ;
	delay(DELAY);
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x0E000000 ;
	delay(DELAY);
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x0F000000 ;
	delay(DELAY);
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x0F800000 ;
	delay(DELAY);
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x0FC00000 ;
	delay(DELAY);
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x0FE00000 ;
	delay(DELAY);
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x0FF00000 ;
	delay(DELAY);
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x0FF80000 ;
	delay(DELAY);
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x0FFC0000 ;
	delay(DELAY);
	IOCLR1 = 0x0FFFF000 ;
	IOSET1 = 0x0FFE0000 ;
	delay(DELAY);
	while ( 1 ) ;
	return 0 ;
}

